name: connect_app
description: A new Flutter application.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  font_awesome_flutter: ^8.10.0
  shimmer: ^1.1.2
  firebase_core: ^0.5.0
  firebase_auth: ^0.18.1+1
  cloud_firestore: ^0.14.1+2
  firebase_storage: ^4.0.1
  image_picker: ^0.6.7+11
  modal_progress_hud: ^0.1.3
  popup_box: ^0.1.0
  cached_network_image: ^2.3.3
  provider: ^4.3.2+2
  multi_image_picker: ^4.7.14
  uuid: 2.2.2
  line_awesome_flutter: ^1.0.1
  transparent_image: ^1.0.0
  get: ^3.24.0
  smooth_star_rating: ^1.1.1
  url_launcher: ^5.7.10



dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:


  uses-material-design: true

  assets:
    - images/


  fonts:
   - family: Pacifico
     fonts:
     - asset: fonts/Pacifico-Regular.ttf


   - family: Nunito
     fonts:
     - asset: fonts/Nunito-Regular.ttf

   - family: Nunito-Bold
     fonts:
     - asset: fonts/Nunito-Bold.ttf

